language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1.16.0
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='-Xcompat.version=2.0'
before_install:
  - if [ "jruby" != "$TRAVIS_RUBY_VERSION"  ]; then gem install bundler; fi
