language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='-Xcompat.version=2.0'
before_install:
  - if [ "jruby" != "$TRAVIS_RUBY_VERSION"  ]; then gem install bundler; fi
