language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='-Xcompat.version=2.0'
before_install:
  - if [ "jruby" != "$TRAVIS_RUBY_VERSION"  ]; then gem install bundler; fi
